name: 'de-zoomcamp-module-4'
version: '1.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
data-paths: ["data"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  de-zoomcamp-module-4:
    staging:
      materialized: view
    intermediate:
      materialized: view
    marts:
      materialized: table
